/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.1.5-dev (node-Sequelize6 dev) on 2021-09-06 12:57:44.
 * Goto
 * https://github.com/mysql-workbench-schema-exporter/mysql-workbench-schema-exporter
 * for more information.
 */

const { DataTypes, Model } = require('sequelize')

class Address extends Model {
}

module.exports = (sequelize, extend) => {
  Address.init(extend({
    id: {
      type: DataTypes.INTEGER,
      field: 'id',
      primaryKey: true,
      autoIncrement: true
    },
    createdAt: {
      type: DataTypes.DATE,
      field: 'created_at',
      allowNull: false,
      defaultValue: sequelize.fn('NOW')
    },
    updatedAt: {
      type: DataTypes.DATE,
      field: 'updated_at',
      allowNull: false,
      defaultValue: sequelize.fn('NOW')
    },
    comment: {
      type: DataTypes.TEXT,
      field: 'comment',
      allowNull: false,
      defaultValue: ''
    },
    label: {
      type: DataTypes.STRING(200),
      field: 'label'
    },
    street: {
      type: DataTypes.STRING(45),
      field: 'street',
      allowNull: false
    },
    zipCode: {
      type: DataTypes.STRING(45),
      field: 'zip_code',
      allowNull: false
    },
    city: {
      type: DataTypes.STRING(45),
      field: 'city',
      allowNull: false
    },
    country: {
      type: DataTypes.STRING(45),
      field: 'country',
      allowNull: false
    }
  }), {
    sequelize: sequelize,
    modelName: 'Address',
    tableName: 'address',
    timestamps: true,
    underscored: true,
    syncOnAssociation: false
  })

  Address.associate = () => {
    // 1 <=> N association
    Address.hasMany(sequelize.models.User, {
      foreignKey: {
        name: 'addressId',
        allowNull: false
      },
      onUpdate: 'CASCADE',
      onDelete: 'RESTRICT',
      targetKey: 'id',
      as: 'Users'
    })
  }

  return Address
}
