/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.1.5-dev (node-Sequelize6 dev) on 2021-09-06 12:57:44.
 * Goto
 * https://github.com/mysql-workbench-schema-exporter/mysql-workbench-schema-exporter
 * for more information.
 */

const { DataTypes, Model } = require('sequelize')

class Group extends Model {
}

module.exports = (sequelize, extend) => {
  Group.init(extend({
    id: {
      type: DataTypes.INTEGER,
      field: 'id',
      primaryKey: true,
      autoIncrement: true
    },
    createdAt: {
      type: DataTypes.DATE,
      field: 'created_at',
      allowNull: false,
      defaultValue: sequelize.fn('NOW')
    },
    updatedAt: {
      type: DataTypes.DATE,
      field: 'updated_at',
      allowNull: false,
      defaultValue: sequelize.fn('NOW')
    },
    name: {
      type: DataTypes.STRING(200),
      field: 'name',
      allowNull: false
    },
    comment: {
      type: DataTypes.TEXT,
      field: 'comment',
      allowNull: false,
      defaultValue: ''
    }
  }), {
    sequelize: sequelize,
    modelName: 'Group',
    tableName: 'group',
    timestamps: true,
    underscored: true,
    syncOnAssociation: false
  })

  Group.associate = () => {
    // N <=> M association
    Group.belongsToMany(sequelize.models.Permission, {
      through: 'group_has_permissions',
      foreignKey: {
        name: 'group_id'
      },
      onUpdate: 'CASCADE',
      onDelete: 'CASCADE',
      targetKey: 'id',
      as: 'Permissions'
    })

    // N <=> M association
    Group.belongsToMany(sequelize.models.User, {
      through: 'group_has_user',
      foreignKey: {
        name: 'group_id'
      },
      onUpdate: 'CASCADE',
      onDelete: 'CASCADE',
      targetKey: 'id',
      as: 'Users'
    })
  }

  return Group
}
