/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.1.5-dev (node-Sequelize6 dev) on 2022-01-18 19:40:59.
 * Goto
 * https://github.com/mysql-workbench-schema-exporter/mysql-workbench-schema-exporter
 * for more information.
 */

const { DataTypes, Model } = require('sequelize')

class Log extends Model {
}

module.exports = (sequelize, extend) => {
  Log.init(extend({
    id: {
      type: DataTypes.INTEGER,
      field: 'id',
      primaryKey: true,
      autoIncrement: true
    },
    createdAt: {
      type: DataTypes.DATE,
      field: 'created_at',
      allowNull: false,
      defaultValue: sequelize.fn('NOW')
    },
    updatedAt: {
      type: DataTypes.DATE,
      field: 'updated_at',
      allowNull: false,
      defaultValue: sequelize.fn('NOW')
    },
    name: {
      type: DataTypes.STRING(200),
      field: 'name',
      allowNull: false,
      defaultValue: ''
    },
    comment: {
      type: DataTypes.TEXT,
      field: 'comment',
      allowNull: false,
      defaultValue: ''
    }
  }), {
    sequelize: sequelize,
    modelName: 'Log',
    tableName: 'log',
    indexes: [
      {
        name: 'log_user_fk1_idx',
        fields: ['user_id']
      }
    ],
    timestamps: true,
    underscored: true,
    syncOnAssociation: false
  })

  Log.associate = () => {
    // N <=> 1 association
    Log.belongsTo(sequelize.models.User, {
      foreignKey: {
        name: 'userId',
        allowNull: true
      },
      onUpdate: 'SET NULL',
      targetKey: 'id'
    })
  }

  return Log
}
